"use client";

import { useMemo, useState } from "react";
import { createBooking } from "@/lib/actions/cms";
import type { BookingServiceRow } from "@/types/database";
import styles from "@/app/(public)/booking/booking.module.css";

const slots=["09:00","11:30","14:00","16:30","19:00"];
const weekdays=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
function iso(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
export default function BookingCalendar({services}:{services:BookingServiceRow[]}){const today=useMemo(()=>{const d=new Date();d.setHours(0,0,0,0);return d},[]);const[month,setMonth]=useState(new Date(today.getFullYear(),today.getMonth(),1));const[date,setDate]=useState("");const[time,setTime]=useState("");const[serviceId,setServiceId]=useState(services[0]?.id??"");const[message,setMessage]=useState("");const[submitting,setSubmitting]=useState(false);const service=services.find(x=>x.id===serviceId)??services[0];
  const days=useMemo(()=>{const start=(month.getDay()+6)%7;const total=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();return [...Array(start).fill(null),...Array.from({length:total},(_,i)=>new Date(month.getFullYear(),month.getMonth(),i+1))]},[month]);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!date||!time||!service){setMessage("Choose a service, date, and time.");return}setSubmitting(true);const fd=new FormData(e.currentTarget);const result=await createBooking({service_id:service.id,service_name:service.name,booking_date:date,start_time:time,duration_minutes:service.duration_minutes,name:String(fd.get("name")||""),email:String(fd.get("email")||""),phone:String(fd.get("phone")||""),company:String(fd.get("company")||""),notes:String(fd.get("notes")||"")});setMessage(result.message);setSubmitting(false);if(result.ok){e.currentTarget.reset();setDate("");setTime("")}}
  return <form className={styles.bookingFlow} onSubmit={submit}><section className={styles.serviceChoice}><p className={styles.stepLabel}>01 · Session</p><div>{services.map(item=><button type="button" className={serviceId===item.id?styles.activeChoice:""} onClick={()=>setServiceId(item.id)} key={item.id}><strong>{item.name}</strong><span>{item.duration_minutes/60} hr · {item.description}</span></button>)}</div></section>
    <section className={styles.calendarSection}><p className={styles.stepLabel}>02 · Date</p><div className={styles.calendarHead}><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>←</button><strong>{month.toLocaleDateString("en-US",{month:"long",year:"numeric"})}</strong><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>→</button></div><div className={styles.weekdays}>{weekdays.map(day=><span key={day}>{day}</span>)}</div><div className={styles.days}>{days.map((day,index)=>{if(!day)return <span key={`blank-${index}`}/>;const disabled=day<today||day.getDay()===0;const value=iso(day);return <button type="button" disabled={disabled} className={date===value?styles.selectedDay:""} onClick={()=>{setDate(value);setTime("")}} key={value}>{day.getDate()}</button>})}</div></section>
    <section className={styles.timeSection}><p className={styles.stepLabel}>03 · Time</p>{date?<div className={styles.slots}>{slots.map(slot=><button type="button" className={time===slot?styles.selectedTime:""} onClick={()=>setTime(slot)} key={slot}>{slot}</button>)}</div>:<p className={styles.emptyState}>Choose a date to see available times.</p>}</section>
    <section className={styles.detailsSection}><p className={styles.stepLabel}>04 · Your details</p><div className={styles.detailGrid}><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Phone<input name="phone" type="tel"/></label><label>Company / artist<input name="company"/></label></div><label className={styles.notes}>Session notes<textarea name="notes" rows={4} placeholder="Tell us what you’re making and what you need in the room."/></label><div className={styles.summary}><span>{service?.name??"Session"}</span><span>{date?new Date(`${date}T12:00:00`).toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"}):"Choose date"}</span><span>{time||"Choose time"}</span></div><button className={styles.submit} disabled={submitting}>{submitting?"Sending request…":"Request booking"}<span>↗</span></button><p className={styles.response} aria-live="polite">{message||"No payment is taken now. The studio will confirm availability and pricing."}</p></section>
  </form>}
