"use client";

import { useState } from "react";
import { updateBookingStatus, updateContactStatus, updateSubscriberStatus } from "@/lib/actions/cms";
import type { BookingRow, ContactSubmissionRow, SubscriberRow } from "@/types/database";

const tableStyle:React.CSSProperties={width:"100%",borderCollapse:"collapse"};const headStyle:React.CSSProperties={padding:"0 12px 12px 0",borderBottom:"1px solid var(--border)",textAlign:"left",fontFamily:"var(--font-geist-mono)",fontSize:"9px",letterSpacing:".08em",textTransform:"uppercase",color:"var(--fg-muted)"};const cellStyle:React.CSSProperties={padding:"17px 12px 17px 0",borderBottom:"1px solid var(--border)",verticalAlign:"top",fontFamily:"var(--font-geist-sans)",fontSize:"13px",color:"var(--fg-primary)"};const selectStyle:React.CSSProperties={background:"var(--bg-elevated)",border:"1px solid var(--border)",color:"var(--fg-muted)",padding:"7px",fontFamily:"var(--font-geist-mono)",fontSize:"9px"};
export function ContactsTable({rows}:{rows:ContactSubmissionRow[]}){const[message,setMessage]=useState("");async function change(id:string,status:ContactSubmissionRow["status"]){const r=await updateContactStatus(id,status);setMessage(r.message)}return <>{message&&<p style={notice}>{message}</p>}<table style={tableStyle}><thead><tr>{["Received","From","Inquiry","Message","Status"].map(x=><th style={headStyle} key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td style={cellStyle}>{new Date(row.created_at).toLocaleDateString()}</td><td style={cellStyle}><strong>{row.name}</strong><small style={small}>{row.email}<br/>{row.company}</small></td><td style={cellStyle}>{row.inquiry_type}</td><td style={{...cellStyle,maxWidth:"380px",lineHeight:1.5}}>{row.message}</td><td style={cellStyle}><select value={row.status} onChange={e=>change(row.id,e.target.value as ContactSubmissionRow["status"])} style={selectStyle}>{["new","in_progress","closed","spam"].map(x=><option key={x}>{x}</option>)}</select></td></tr>)}</tbody></table></>}
export function SubscribersTable({rows}:{rows:SubscriberRow[]}){const[message,setMessage]=useState("");async function change(id:string,status:SubscriberRow["status"]){const r=await updateSubscriberStatus(id,status);setMessage(r.message)}return <>{message&&<p style={notice}>{message}</p>}<table style={tableStyle}><thead><tr>{["Email","Source","Subscribed","Status"].map(x=><th style={headStyle} key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td style={cellStyle}>{row.email}</td><td style={cellStyle}>{row.source}</td><td style={cellStyle}>{new Date(row.subscribed_at).toLocaleDateString()}</td><td style={cellStyle}><select value={row.status} onChange={e=>change(row.id,e.target.value as SubscriberRow["status"])} style={selectStyle}><option>active</option><option>unsubscribed</option></select></td></tr>)}</tbody></table></>}
export function BookingsTable({rows}:{rows:BookingRow[]}){const[message,setMessage]=useState("");async function change(id:string,status:BookingRow["status"]){const r=await updateBookingStatus(id,status);setMessage(r.message)}return <>{message&&<p style={notice}>{message}</p>}<table style={tableStyle}><thead><tr>{["Date / time","Service","Client","Notes","Status"].map(x=><th style={headStyle} key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td style={cellStyle}><strong>{new Date(`${row.booking_date}T12:00:00`).toLocaleDateString()}</strong><small style={small}>{row.start_time.slice(0,5)} · {row.duration_minutes} min</small></td><td style={cellStyle}>{row.service_name}</td><td style={cellStyle}><strong>{row.name}</strong><small style={small}>{row.email}<br/>{row.phone}</small></td><td style={{...cellStyle,maxWidth:"300px"}}>{row.notes||"—"}</td><td style={cellStyle}><select value={row.status} onChange={e=>change(row.id,e.target.value as BookingRow["status"])} style={selectStyle}>{["pending","confirmed","completed","cancelled"].map(x=><option key={x}>{x}</option>)}</select></td></tr>)}</tbody></table></>}
const small:React.CSSProperties={display:"block",marginTop:"5px",fontFamily:"var(--font-geist-mono)",fontSize:"9px",lineHeight:1.5,color:"var(--fg-muted)"};const notice:React.CSSProperties={padding:"10px 12px",background:"rgba(212,255,62,.08)",color:"var(--accent-highlight)",fontFamily:"var(--font-geist-mono)",fontSize:"10px"};
