"use client";

import { useState } from "react";
import ImageUpload from "@/components/admin/ImageUpload";
import WysiwygEditor from "@/components/admin/WysiwygEditor";
import { deleteTeamMember, saveTeamMember } from "@/lib/actions/cms";
import type { TeamMemberRow } from "@/types/database";

const empty={name:"",role:"",bio_html:"<p></p>",image_url:"",display_order:0,published:true};
export default function TeamManager({members}:{members:TeamMemberRow[]}){const [selected,setSelected]=useState<TeamMemberRow|null>(null);const [form,setForm]=useState(empty);const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);
  function edit(member:TeamMemberRow){setSelected(member);setForm({name:member.name,role:member.role,bio_html:member.bio_html,image_url:member.image_url??"",display_order:member.display_order,published:member.published})}
  function reset(){setSelected(null);setForm(empty)}
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);const result=await saveTeamMember(selected?.id??null,form);setMessage(result.message);setSaving(false);if(result.ok)window.location.reload()}
  async function remove(){if(!selected||!confirm("Remove this team member?"))return;const result=await deleteTeamMember(selected.id);if(result.ok)window.location.reload();else setMessage(result.message)}
  return <div style={{display:"grid",gridTemplateColumns:"minmax(260px,.7fr) minmax(0,1.3fr)",gap:"64px"}}><section><button onClick={reset} style={addStyle}>+ Add team member</button><div style={{marginTop:"20px",borderTop:"1px solid var(--border)"}}>{members.map(member=><button onClick={()=>edit(member)} key={member.id} style={{...memberStyle,color:selected?.id===member.id?"var(--accent-highlight)":"var(--fg-primary)"}}><span>{member.name}</span><small>{member.role}</small></button>)}</div></section><form onSubmit={submit}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"24px"}}><label style={labelStyle}>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} style={inputStyle}/></label><label style={labelStyle}>Role<input required value={form.role} onChange={e=>setForm({...form,role:e.target.value})} style={inputStyle}/></label></div><div style={{marginTop:"30px"}}><ImageUpload bucket="site-media" label="Portrait" value={form.image_url} onChange={value=>setForm({...form,image_url:value})}/></div><div style={{marginTop:"30px"}}><WysiwygEditor label="Biography" value={form.bio_html} onChange={value=>setForm({...form,bio_html:value})}/></div><div style={{display:"flex",gap:"24px",marginTop:"24px"}}><label style={checkStyle}>Order <input type="number" value={form.display_order} onChange={e=>setForm({...form,display_order:Number(e.target.value)})} style={{width:"54px"}}/></label><label style={checkStyle}><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Published</label></div>{message&&<p style={{fontFamily:"var(--font-geist-mono)",fontSize:"11px",color:"var(--fg-muted)"}}>{message}</p>}<div style={{display:"flex",gap:"10px",marginTop:"30px"}}><button disabled={saving} style={addStyle}>{saving?"Saving…":"Save member"}</button>{selected&&<button type="button" onClick={remove} style={{...addStyle,background:"transparent",color:"#ff7d7d",border:"1px solid var(--border)"}}>Remove</button>}</div></form></div>}
const addStyle:React.CSSProperties={padding:"12px 18px",border:0,background:"var(--accent-highlight)",color:"#080808",cursor:"pointer",fontFamily:"var(--font-geist-mono)",fontSize:"10px",fontWeight:700,textTransform:"uppercase"};
const memberStyle:React.CSSProperties={display:"block",width:"100%",padding:"17px 0",border:0,borderBottom:"1px solid var(--border)",background:"transparent",textAlign:"left",cursor:"pointer",fontFamily:"var(--font-geist-sans)",fontSize:"14px"};
const labelStyle:React.CSSProperties={fontFamily:"var(--font-geist-mono)",fontSize:"10px",color:"var(--fg-muted)",textTransform:"uppercase"};
const inputStyle:React.CSSProperties={display:"block",width:"100%",marginTop:"8px",padding:"10px 0",border:0,borderBottom:"1px solid var(--admin-input-border)",background:"transparent",color:"var(--fg-primary)",outline:0};
const checkStyle:React.CSSProperties={display:"flex",alignItems:"center",gap:"8px",fontFamily:"var(--font-geist-mono)",fontSize:"10px",color:"var(--fg-muted)",textTransform:"uppercase"};
