import type { Project } from "@/types";

export const projects: Project[] = [
  {
    slug: "ritual-of-motion",
    title: "Ritual of Motion",
    category: "Brand",
    client: "Adidas Africa",
    year: 2024,
    muxPlaybackId: "VCBESmjDlV4eRLTFzQ2j75KtN1XrKyV9sdwaAQXNv38",
    aspectRatio: "4:3",
    gridSize: "large",
    featured: true,
  },
  {
    slug: "the-last-frontier",
    title: "The Last Frontier",
    category: "Narrative",
    client: "Netflix Africa",
    year: 2024,
    muxPlaybackId: "CkqEBNBjOnsS5xdeHV9VakK2k8j1j500FATUoIAWnnv4",
    aspectRatio: "4:3",
    gridSize: "large",
    featured: true,
  },
  {
    slug: "frequency",
    title: "Frequency",
    category: "Music",
    client: "Burna Boy",
    year: 2024,
    muxPlaybackId: "zFaTv2EtIEW3dzkNTxBzHvcCJPEG009AR61Ng8h2RPGI",
    aspectRatio: "16:9",
    gridSize: "medium",
    featured: false,
  },
  {
    slug: "heritage-drop",
    title: "Heritage Drop",
    category: "Brand",
    client: "Johnnie Walker",
    year: 2024,
    muxPlaybackId: "00uZ5D3R3y7XM7J67GBZQCBe89j02E1uL01HZ8MW2ocBUc",
    aspectRatio: "16:9",
    gridSize: "medium",
    featured: false,
  },
  {
    slug: "isoka",
    title: "Isoka",
    category: "Narrative",
    year: 2024,
    muxPlaybackId: "KN702xowBcoN1Qq7NKudjBv1l02HMkW2QMkHAlmY7jsak",
    aspectRatio: "1:1",
    gridSize: "small",
    featured: false,
  },
  {
    slug: "golden-hour",
    title: "Golden Hour",
    category: "Music",
    client: "Ayra Starr",
    year: 2024,
    muxPlaybackId: "q3ld4vu00a9IeOlIQFuj6jltcdbS1MM102yz2Of1n601t4",
    aspectRatio: "1:1",
    gridSize: "small",
    featured: false,
  },
];
