import type { Project } from "@/types";

export const projects: Project[] = [
  {
    slug: "ritual-of-motion",
    title: "Ritual of Motion",
    category: "Brand",
    client: "Adidas Africa",
    year: 2024,
    muxPlaybackId: "PLACEHOLDER_MUX_ID_1",
    aspectRatio: "4:3",
    gridSize: "large",
    featured: true,
  },
  {
    slug: "the-last-frontier",
    title: "The Last Frontier",
    category: "Narrative",
    client: "Netflix Africa",
    year: 2024,
    muxPlaybackId: "PLACEHOLDER_MUX_ID_2",
    aspectRatio: "4:3",
    gridSize: "large",
    featured: true,
  },
  {
    slug: "frequency",
    title: "Frequency",
    category: "Music",
    client: "Burna Boy",
    year: 2024,
    muxPlaybackId: "PLACEHOLDER_MUX_ID_3",
    aspectRatio: "16:9",
    gridSize: "medium",
    featured: false,
  },
  {
    slug: "heritage-drop",
    title: "Heritage Drop",
    category: "Brand",
    client: "Johnnie Walker",
    year: 2024,
    muxPlaybackId: "PLACEHOLDER_MUX_ID_4",
    aspectRatio: "16:9",
    gridSize: "medium",
    featured: false,
  },
  {
    slug: "isoka",
    title: "Isoka",
    category: "Narrative",
    year: 2024,
    muxPlaybackId: "PLACEHOLDER_MUX_ID_5",
    aspectRatio: "1:1",
    gridSize: "small",
    featured: false,
  },
  {
    slug: "golden-hour",
    title: "Golden Hour",
    category: "Music",
    client: "Ayra Starr",
    year: 2024,
    muxPlaybackId: "PLACEHOLDER_MUX_ID_6",
    aspectRatio: "1:1",
    gridSize: "small",
    featured: false,
  },
];
